services:
  vohive:
    image: dahai1993/vohive:latest
    container_name: vohive
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: Asia/Shanghai
      CONFIG_PATH: /app/config/config.yaml
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - /dev:/dev

